//! Smoke test: exercises the same FFmpeg filter graph and argument
//! builder that production rendering uses, with placeholder visuals
//! (solid-color PNGs) and silent audio (m4a) generated by ffmpeg.
//!
//! Run with:  cargo run --example smoke
//!
//! Requires ffmpeg + ffprobe on PATH.
//!
//! Verifies both outputs with ffprobe (video stream + audio stream +
//! correct resolution). Exits non-zero if anything fails.

use pdf2vid_lib::render::build_ffmpeg_args;
use serde::Deserialize;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, serde::Serialize, Deserialize)]
struct FfprobeStream {
    codec_type: String,
    width: Option<u32>,
    height: Option<u32>,
}

#[derive(Debug, serde::Serialize, Deserialize)]
struct FfprobeFormat {
    duration: Option<String>,
    size: Option<String>,
}

#[derive(Debug, serde::Serialize, Deserialize)]
struct FfprobeResult {
    streams: Vec<FfprobeStream>,
    format: FfprobeFormat,
}

#[derive(Debug, serde::Serialize)]
struct SmokeOutput {
    path: String,
    bytes: u64,
    ffprobe: FfprobeResult,
    ok: bool,
    issues: Vec<String>,
}

#[derive(Debug, serde::Serialize)]
struct SmokeResult {
    pass: bool,
    youtube: SmokeOutput,
    tiktok: SmokeOutput,
    duration_seconds: f64,
}

fn main() {
    match run() {
        Ok(result) => {
            println!("{}", serde_json::to_string_pretty(&result).unwrap());
            if !result.pass {
                std::process::exit(1);
            }
        }
        Err(e) => {
            eprintln!("smoke test failed to run: {e}");
            std::process::exit(2);
        }
    }
}

fn run() -> Result<SmokeResult, String> {
    let work_dir = std::env::temp_dir().join("pdf2vid-smoke");
    let _ = std::fs::remove_dir_all(&work_dir);
    std::fs::create_dir_all(&work_dir).map_err(|e| format!("mkdir work: {e}"))?;

    let ffmpeg = which("ffmpeg").ok_or_else(|| "ffmpeg not on PATH".to_string())?;
    let ffprobe = which("ffprobe").ok_or_else(|| "ffprobe not on PATH".to_string())?;
    // Copy a system font into the work dir so the drawtext filter can
    // reference it by filename alone (the colon in C:\Windows\... trips
    // ffmpeg's option parser).
    let font_src = locate_fontfile().ok_or_else(|| "no system font found".to_string())?;
    let font_dst = work_dir.join("font.ttf");
    std::fs::copy(&font_src, &font_dst).map_err(|e| format!("copy font: {e}"))?;
    let fontfile = font_dst
        .file_name()
        .and_then(|s| s.to_str())
        .ok_or_else(|| "bad font path".to_string())?
        .to_string();

    let scenes: [f64; 3] = [2.0, 3.0, 2.0];

    // Generate three solid-color visuals and three silent audio tracks.
    let mut visual_paths: Vec<PathBuf> = Vec::new();
    let mut audio_paths: Vec<PathBuf> = Vec::new();
    for (idx, dur) in scenes.iter().enumerate() {
        let v = work_dir.join(format!("scene-{idx}.png"));
        run_ffmpeg(
            &ffmpeg,
            &[
                "-y".into(),
                "-f".into(),
                "lavfi".into(),
                "-i".into(),
                "color=c=red:s=1920x1080:d=1".into(),
                "-frames:v".into(),
                "1".into(),
                v.to_string_lossy().to_string(),
            ],
        )?;
        visual_paths.push(v);

        let a = work_dir.join(format!("scene-{idx}.m4a"));
        run_ffmpeg(
            &ffmpeg,
            &[
                "-y".into(),
                "-f".into(),
                "lavfi".into(),
                "-i".into(),
                format!("anullsrc=r=44100:cl=mono:d={dur}"),
                "-c:a".into(),
                "aac".into(),
                "-b:a".into(),
                "96k".into(),
                "-shortest".into(),
                a.to_string_lossy().to_string(),
            ],
        )?;
        audio_paths.push(a);
    }

    let youtube_out = work_dir.join("sample-youtube.mp4");
    let tiktok_out = work_dir.join("sample-tiktok.mp4");

    // Use the real builder, then override -preset ultrafast for smoke-test
    // speed. The codec/format flags are unchanged.
    let (inputs_y, filter_y) = build_render_filter(&scenes, &visual_paths, &audio_paths, 1920, 1080, &fontfile, false);
    let mut args_y = build_ffmpeg_args(&inputs_y, &filter_y, &youtube_out);
    override_preset(&mut args_y, "ultrafast");
    run_ffmpeg(&ffmpeg, &args_y)?;

    let (inputs_t, filter_t) = build_render_filter(&scenes, &visual_paths, &audio_paths, 1080, 1920, &fontfile, false);
    let mut args_t = build_ffmpeg_args(&inputs_t, &filter_t, &tiktok_out);
    override_preset(&mut args_t, "ultrafast");
    run_ffmpeg(&ffmpeg, &args_t)?;

    let youtube = verify(&ffprobe, &youtube_out, 1920, 1080)?;
    let tiktok = verify(&ffprobe, &tiktok_out, 1080, 1920)?;

    let total_duration: f64 = scenes.iter().sum();
    let pass = youtube.ok && tiktok.ok;

    Ok(SmokeResult {
        pass,
        youtube,
        tiktok,
        duration_seconds: total_duration,
    })
}

/// Build the filter graph exactly as production does. Returns the
/// inputs list and the filter string. The `loop_visual` flag toggles
/// `-loop 1` on the visual inputs; the smoke test sets it to false
/// because each PNG already represents a finite input image.
fn build_render_filter(
    scenes: &[f64],
    visuals: &[PathBuf],
    audios: &[PathBuf],
    w: u32,
    h: u32,
    fontfile: &str,
    loop_visual: bool,
) -> (Vec<String>, String) {
    let mut inputs: Vec<String> = Vec::new();
    let mut filter = String::new();
    let mut audio_inputs = Vec::new();

    for (i, dur) in scenes.iter().enumerate() {
        let visual = &visuals[i];
        let audio = &audios[i];

        if loop_visual {
            inputs.extend([
                "-loop".into(),
                "1".into(),
                "-i".into(),
                visual.to_string_lossy().to_string(),
            ]);
        } else {
            inputs.extend(["-i".into(), visual.to_string_lossy().to_string()]);
        }
        inputs.extend(["-i".into(), audio.to_string_lossy().to_string()]);

        let v_idx = i * 2;
        let a_idx = i * 2 + 1;
        let seconds = (*dur).max(1.0) as u32;
        let script = format!("Page {}", i + 1);
        let safe_script = sanitize_drawtext(&script);
        filter.push_str(&format!(
            "[{v_idx}:v]scale={w}:{h}:force_original_aspect_ratio=decrease,pad={w}:{h}:(ow-iw)/2:(oh-ih)/2:black,zoompan=z='min(zoom+0.0008,1.15)':d={seconds}*25:s={w}x{h},drawtext=fontfile={fontfile}:text='{safe_script}':fontcolor=white:fontsize=42:box=1:boxcolor=black@0.55:boxborderw=14:x=(w-text_w)/2:y=h-80[v{i}];",
        ));
        filter.push_str(&format!("[{a_idx}:a]aresample=44100[a{i}];"));
        audio_inputs.push(format!("[v{i}][a{i}]"));
    }
    filter.push_str(&format!(
        "{}concat=n={}:v=1:a=1[vout][aout]",
        audio_inputs.join(""),
        audio_inputs.len()
    ));
    (inputs, filter)
}

fn override_preset(args: &mut Vec<String>, preset: &str) {
    // build_ffmpeg_args emits ["-preset", "fast"]; rewrite to use the
    // requested preset without disturbing surrounding flags.
    if let Some(i) = args.iter().position(|a| a == "-preset") {
        if let Some(v) = args.get_mut(i + 1) {
            *v = preset.to_string();
        }
    }
}

fn sanitize_drawtext(text: &str) -> String {
    text.replace('\\', "\\\\")
        .replace(':', "\\:")
        .replace('\'', "")
        .replace('%', "\\%")
}

fn run_ffmpeg(ffmpeg: &Path, args: &[String]) -> Result<(), String> {
    let out = Command::new(ffmpeg)
        .args(args)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::piped())
        .output()
        .map_err(|e| format!("spawn ffmpeg: {e}"))?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        eprintln!("--- ffmpeg stderr ---\n{}--- end ---", stderr);
        return Err(format!("ffmpeg failed (exit {:?})", out.status.code()));
    }
    Ok(())
}

fn verify(ffprobe: &Path, path: &Path, want_w: u32, want_h: u32) -> Result<SmokeOutput, String> {
    let meta = std::fs::metadata(path).map_err(|e| format!("stat {path:?}: {e}"))?;
    let raw = Command::new(ffprobe)
        .args([
            "-v", "error",
            "-show_streams",
            "-show_format",
            "-of", "json",
        ])
        .arg(path)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .map_err(|e| format!("spawn ffprobe: {e}"))?;
    if !raw.status.success() {
        return Err(format!(
            "ffprobe failed for {path:?}: {}",
            String::from_utf8_lossy(&raw.stderr)
        ));
    }
    let parsed: FfprobeResult = serde_json::from_slice(&raw.stdout)
        .map_err(|e| format!("ffprobe json parse: {e}"))?;

    let mut issues = Vec::new();
    let video_streams: Vec<_> = parsed
        .streams
        .iter()
        .filter(|s| s.codec_type == "video")
        .collect();
    let audio_streams: Vec<_> = parsed
        .streams
        .iter()
        .filter(|s| s.codec_type == "audio")
        .collect();

    if video_streams.is_empty() {
        issues.push("no video stream".into());
    }
    if audio_streams.is_empty() {
        issues.push("no audio stream".into());
    }
    if let Some(v) = video_streams.first() {
        match (v.width, v.height) {
            (Some(w), Some(h)) if w == want_w && h == want_h => {}
            (Some(w), Some(h)) => {
                issues.push(format!("resolution {w}x{h} != {want_w}x{want_h}"))
            }
            _ => issues.push("video stream missing width/height".into()),
        }
    }

    Ok(SmokeOutput {
        path: path.to_string_lossy().to_string(),
        bytes: meta.len(),
        ffprobe: parsed,
        ok: issues.is_empty(),
        issues,
    })
}

fn which(name: &str) -> Option<PathBuf> {
    let paths = std::env::var_os("PATH")?;
    for path in std::env::split_paths(&paths) {
        for ext in ["", ".exe", ".bat", ".cmd"] {
            let candidate = path.join(format!("{name}{ext}"));
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}

fn locate_fontfile() -> Option<String> {
    // Search common font locations on each platform.
    let candidates: Vec<String> = if cfg!(windows) {
        vec![
            "C:/Windows/Fonts/arial.ttf".into(),
            "C:/Windows/Fonts/segoeui.ttf".into(),
            "C:/Windows/Fonts/consola.ttf".into(),
        ]
    } else if cfg!(target_os = "macos") {
        vec![
            "/System/Library/Fonts/Helvetica.ttc".into(),
            "/Library/Fonts/Arial.ttf".into(),
        ]
    } else {
        vec![
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf".into(),
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf".into(),
        ]
    };
    for c in candidates {
        if std::path::Path::new(&c).is_file() {
            // drawtext expects forward-slash paths on Windows.
            return Some(c.replace('\\', "/"));
        }
    }
    None
}