//! Smoke test: exercises the same FFmpeg filter graph and argument
//! builder that production rendering uses, with placeholder visuals
//! (solid-color PNGs) and silent audio (m4a) generated by ffmpeg.
//!
//! Run with:  cargo run --example smoke
//! Run with a custom font: cargo run --example smoke -- --font /path/to/font.ttf
//!
////! Requires ffmpeg + ffprobe on PATH.
//!
//! Verifies both outputs with ffprobe (video stream + audio stream +
//! correct resolution). Exits non-zero if anything fails.

use pdf2vid_lib::font::{resolve_font, FontResolution};
use pdf2vid_lib::render::build_ffmpeg_args;
use serde::Deserialize;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, serde::Serialize, Deserialize)]
struct FfprobeStream {
    codec_type: String,
    width: Option<u32>,
    height: Option<u32>,
}

#[derive(Debug, serde::Serialize, Deserialize)]
struct FfprobeFormat {
    duration: Option<String>,
    size: Option<String>,
}

#[derive(Debug, serde::Serialize, Deserialize)]
struct FfprobeResult {
    streams: Vec<FfprobeStream>,
    format: FfprobeFormat,
}

#[derive(Debug, serde::Serialize)]
struct SmokeOutput {
    path: String,
    bytes: u64,
    ffprobe: FfprobeResult,
    ok: bool,
    issues: Vec<String>,
}

#[derive(Debug, serde::Serialize)]
struct SmokeResult {
    pass: bool,
    youtube: SmokeOutput,
    tiktok: SmokeOutput,
    duration_seconds: f64,
    /// `None` when a usable font was discovered and used; `Some(message)`
    /// when the smoke test fell back to text-less drawtext. This mirrors
    /// the production `render_fallback_used` flag.
    font_warning: Option<String>,
    /// The render path handed to FFmpeg (`font.ttf` in the work dir, or
    /// `None` when no font was found).
    font_path: Option<String>,
}

fn main() {
    match run() {
        Ok(result) => {
            println!("{}", serde_json::to_string_pretty(&result).unwrap());
            if !result.pass {
                std::process::exit(1);
            }
        }
        Err(e) => {
            eprintln!("smoke test failed to run: {e}");
            std::process::exit(2);
        }
    }
}

struct Args {
    /// Optional override for the font discovery. When `Some`, the smoke
    /// test uses this path instead of the platform default. Used by
    /// `--font` from the CLI and by the integration test that wants to
    /// reproduce a missing-font failure.
    font: Option<PathBuf>,
}

fn parse_args() -> Args {
    let mut args = Args { font: None };
    let mut iter = std::env::args().skip(1);
    while let Some(arg) = iter.next() {
        match arg.as_str() {
            "--font" => {
                if let Some(v) = iter.next() {
                    args.font = Some(PathBuf::from(v));
                }
            }
            other => eprintln!("warning: unknown argument {other}"),
        }
    }
    args
}

fn run() -> Result<SmokeResult, String> {
    let args = parse_args();
    let work_dir = std::env::temp_dir().join("pdf2vid-smoke");
    let _ = std::fs::remove_dir_all(&work_dir);
    std::fs::create_dir_all(&work_dir).map_err(|e| format!("mkdir work: {e}"))?;

    let ffmpeg = which("ffmpeg").ok_or_else(|| "ffmpeg not on PATH".to_string())?;
    let ffprobe = which("ffprobe").ok_or_else(|| "ffprobe not on PATH".to_string())?;

    // Resolve the font exactly the way production does. If the user
    // passed --font, we stage that file under `font.ttf` instead so the
    // FFmpeg filter parser sees a safe local path.
    let font_resolution = resolve_smoke_font(&args, &work_dir);
    let font_for_ffmpeg = font_resolution
        .render_path
        .as_deref()
        .map(|p| pdf2vid_lib::font::escape_fontfile_for_filter(p));
    let font_warning = if font_resolution.found {
        None
    } else {
        Some(font_resolution.message.clone())
    };

    let scenes: [f64; 3] = [2.0, 3.0, 2.0];

    // Generate three solid-color visuals and three silent audio tracks.
    let mut visual_paths: Vec<PathBuf> = Vec::new();
    let mut audio_paths: Vec<PathBuf> = Vec::new();
    for (idx, dur) in scenes.iter().enumerate() {
        let v = work_dir.join(format!("scene-{idx}.png"));
        run_ffmpeg(
            &ffmpeg,
            &[
                "-y".into(),
                "-f".into(),
                "lavfi".into(),
                "-i".into(),
                "color=c=red:s=1920x1080:d=1".into(),
                "-frames:v".into(),
                "1".into(),
                v.to_string_lossy().to_string(),
            ],
        )?;
        visual_paths.push(v);

        let a = work_dir.join(format!("scene-{idx}.m4a"));
        run_ffmpeg(
            &ffmpeg,
            &[
                "-y".into(),
                "-f".into(),
                "lavfi".into(),
                "-i".into(),
                format!("anullsrc=r=44100:cl=mono:d={dur}"),
                "-c:a".into(),
                "aac".into(),
                "-b:a".into(),
                "96k".into(),
                "-shortest".into(),
                a.to_string_lossy().to_string(),
            ],
        )?;
        audio_paths.push(a);
    }

    let youtube_out = work_dir.join("sample-youtube.mp4");
    let tiktok_out = work_dir.join("sample-tiktok.mp4");

    // Build the filter graph the same way production does. The only
    // difference is `loop_visual=false` because each PNG already
    // represents a finite input image — no need for `-loop 1` in the
    // smoke harness.
    let (inputs_y, filter_y) =
        build_render_filter(&scenes, &visual_paths, &audio_paths, 1920, 1080);
    let mut args_y = build_ffmpeg_args(
        &inputs_y,
        &filter_y,
        &youtube_out,
        font_for_ffmpeg.as_deref(),
    );
    override_preset(&mut args_y, "ultrafast");
    run_ffmpeg(&ffmpeg, &args_y)?;

    let (inputs_t, filter_t) =
        build_render_filter(&scenes, &visual_paths, &audio_paths, 1080, 1920);
    let mut args_t = build_ffmpeg_args(
        &inputs_t,
        &filter_t,
        &tiktok_out,
        font_for_ffmpeg.as_deref(),
    );
    override_preset(&mut args_t, "ultrafast");
    run_ffmpeg(&ffmpeg, &args_t)?;

    let youtube = verify(&ffprobe, &youtube_out, 1920, 1080)?;
    let tiktok = verify(&ffprobe, &tiktok_out, 1080, 1920)?;

    let total_duration: f64 = scenes.iter().sum();
    let pass = youtube.ok && tiktok.ok;

    Ok(SmokeResult {
        pass,
        youtube,
        tiktok,
        duration_seconds: total_duration,
        font_warning,
        font_path: font_resolution.render_path,
    })
}

/// Resolve the font for the smoke test, honoring `--font` overrides.
fn resolve_smoke_font(args: &Args, work_dir: &Path) -> FontResolution {
    if let Some(override_path) = &args.font {
        if !override_path.is_file() {
            return FontResolution {
                found: false,
                source_path: None,
                render_path: None,
                render_kind: pdf2vid_lib::font::FontRenderKind::None,
                message: format!(
                    "--font {} does not exist or is not a file",
                    override_path.display()
                ),
                install_hint: Some(
                    "Pass a valid .ttf path, or omit --font to use platform defaults.".into(),
                ),
            };
        }
        // Stage the override into the work dir so the filter parser
        // sees the same safe filename production uses.
        match pdf2vid_lib::font::stage_font_for_render(override_path, work_dir) {
            Ok(staged) => FontResolution {
                found: true,
                source_path: Some(override_path.to_string_lossy().to_string()),
                render_path: Some(staged),
                render_kind: pdf2vid_lib::font::FontRenderKind::Workdir,
                message: format!("Using override font {}", override_path.display()),
                install_hint: None,
            },
            Err(e) => FontResolution {
                found: false,
                source_path: Some(override_path.to_string_lossy().to_string()),
                render_path: None,
                render_kind: pdf2vid_lib::font::FontRenderKind::None,
                message: format!("Could not stage override font: {e}"),
                install_hint: Some("Pass a readable .ttf path.".into()),
            },
        }
    } else {
        resolve_font(work_dir)
    }
}

/// Build the filter graph exactly as production does. Returns the
/// inputs list and the filter string. drawtext uses the font already
/// injected by `build_ffmpeg_args` — this function only builds the
/// per-scene filter clauses without a hard-coded `fontfile=`.
fn build_render_filter(
    scenes: &[f64],
    visuals: &[PathBuf],
    audios: &[PathBuf],
    w: u32,
    h: u32,
) -> (Vec<String>, String) {
    let mut inputs: Vec<String> = Vec::new();
    let mut filter = String::new();
    let mut audio_inputs = Vec::new();

    for (i, dur) in scenes.iter().enumerate() {
        let visual = &visuals[i];
        let audio = &audios[i];

        // No `-loop 1` in the smoke test: each PNG is a finite image.
        inputs.extend(["-i".into(), visual.to_string_lossy().to_string()]);
        inputs.extend(["-i".into(), audio.to_string_lossy().to_string()]);

        let v_idx = i * 2;
        let a_idx = i * 2 + 1;
        let seconds = (*dur).max(1.0) as u32;
        let script = format!("Page {}", i + 1);
        let safe_script = sanitize_drawtext(&script);
        filter.push_str(&format!(
            "[{v_idx}:v]scale={w}:{h}:force_original_aspect_ratio=decrease,pad={w}:{h}:(ow-iw)/2:(oh-ih)/2:black,zoompan=z='min(zoom+0.0008,1.15)':d={seconds}*25:s={w}x{h},drawtext=text='{safe_script}':fontcolor=white:fontsize=42:box=1:boxcolor=black@0.55:boxborderw=14:x=(w-text_w)/2:y=h-80[v{i}];",
        ));
        filter.push_str(&format!("[{a_idx}:a]aresample=44100[a{i}];"));
        audio_inputs.push(format!("[v{i}][a{i}]"));
    }
    filter.push_str(&format!(
        "{}concat=n={}:v=1:a=1[vout][aout]",
        audio_inputs.join(""),
        audio_inputs.len()
    ));
    (inputs, filter)
}

fn override_preset(args: &mut [String], preset: &str) {
    // build_ffmpeg_args emits ["-preset", "fast"]; rewrite to use the
    // requested preset without disturbing surrounding flags.
    if let Some(i) = args.iter().position(|a| a == "-preset") {
        if let Some(v) = args.get_mut(i + 1) {
            *v = preset.to_string();
        }
    }
}

fn sanitize_drawtext(text: &str) -> String {
    text.replace('\\', "\\\\")
        .replace(':', "\\:")
        .replace('\'', "")
        .replace('%', "\\%")
}

fn run_ffmpeg(ffmpeg: &Path, args: &[String]) -> Result<(), String> {
    let out = Command::new(ffmpeg)
        .args(args)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::piped())
        .output()
        .map_err(|e| format!("spawn ffmpeg: {e}"))?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        eprintln!("--- ffmpeg stderr ---\n{}--- end ---", stderr);
        return Err(format!("ffmpeg failed (exit {:?})", out.status.code()));
    }
    Ok(())
}

fn verify(ffprobe: &Path, path: &Path, want_w: u32, want_h: u32) -> Result<SmokeOutput, String> {
    let meta = std::fs::metadata(path).map_err(|e| format!("stat {path:?}: {e}"))?;
    let raw = Command::new(ffprobe)
        .args([
            "-v",
            "error",
            "-show_streams",
            "-show_format",
            "-of",
            "json",
        ])
        .arg(path)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .map_err(|e| format!("spawn ffprobe: {e}"))?;
    if !raw.status.success() {
        return Err(format!(
            "ffprobe failed for {path:?}: {}",
            String::from_utf8_lossy(&raw.stderr)
        ));
    }
    let parsed: FfprobeResult =
        serde_json::from_slice(&raw.stdout).map_err(|e| format!("ffprobe json parse: {e}"))?;

    let mut issues = Vec::new();
    let video_streams: Vec<_> = parsed
        .streams
        .iter()
        .filter(|s| s.codec_type == "video")
        .collect();
    let audio_streams: Vec<_> = parsed
        .streams
        .iter()
        .filter(|s| s.codec_type == "audio")
        .collect();

    if video_streams.is_empty() {
        issues.push("no video stream".into());
    }
    if audio_streams.is_empty() {
        issues.push("no audio stream".into());
    }
    if let Some(v) = video_streams.first() {
        match (v.width, v.height) {
            (Some(w), Some(h)) if w == want_w && h == want_h => {}
            (Some(w), Some(h)) => issues.push(format!("resolution {w}x{h} != {want_w}x{want_h}")),
            _ => issues.push("video stream missing width/height".into()),
        }
    }

    // Bound the duration: the smoke fixtures sum to 7s and ffmpeg
    // shouldn't produce a runaway file. Accept anything up to 30s.
    if let Some(dur) = parsed
        .format
        .duration
        .as_deref()
        .and_then(|s| s.parse::<f64>().ok())
    {
        if !(0.5..=30.0).contains(&dur) || !dur.is_finite() {
            issues.push(format!("duration {dur}s out of bounds or non-finite"));
        }
    }

    Ok(SmokeOutput {
        path: path.to_string_lossy().to_string(),
        bytes: meta.len(),
        ffprobe: parsed,
        ok: issues.is_empty(),
        issues,
    })
}

fn which(name: &str) -> Option<PathBuf> {
    let paths = std::env::var_os("PATH")?;
    for path in std::env::split_paths(&paths) {
        for ext in ["", ".exe", ".bat", ".cmd"] {
            let candidate = path.join(format!("{name}{ext}"));
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}
